print("And I'd give up forever to touch you \n"
"Cause I know that you feel me somehow\n"
"You're the closest to heaven that I'll ever be\n"
"And I don't want to go home right now\n"
"And all I can taste is this moment\n"
"And all I can breathe is your life\n"
"And sooner or later, it's over\n"
"I just don't wanna miss you tonight\n"
"And I don't want the world to see me\n"
"Cause I don't think that they'd understand\n"
"When everything's made to be broken\n"
"I just want you to know who I am\n"
"And you can't fight the tears that ain't coming\n"
"Or the moment of truth in your lies\n"
"When everything feels like the movies"
"Yeah, you bleed just to know, you're alive\n"
"And I don't want the world to see me\n"
"Cause I don't think that they'd understand\n"
"When everything's made to be broken\n"
"I just want you to know who I am\n"
"And I don't want the world to see me\n"
"Cause I don't think that they'd understand\n"
"When everything's made to be broken\n"
"I just want you to know who I am\n"
"And I don't want the world to see me\n"
"Cause I don't think that they'd understand\n"
"When everything's made to be broken\n"
"I just want you to know who I am\n"
"I just want you to know who I am\n"
"I just want you to know who I am\n"
"I just want you to know who I am")